version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: wilfridbnz
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: wilfrid
      MYSQL_PASSWORD: mypassword
    expose:
      - 3306
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: wilfridbnz
    ports:
      - "8080:80"

volumes:
  mysql_data: